import {Hono} from 'hono'; import type {Context,Next} from 'hono'; import QRCode from 'qrcode'; import type {AppEnv} from '../types'; import {layout} from '../ui/layout'; import {body,esc,ip,jsonError} from '../utils/http'; import {qrMatrixToPng} from '../utils/png'; import {requireAdmin} from '../auth/session'; import {randomToken,sha256,verifyPassword} from '../utils/crypto'; import {castAnonymousVote,electionState,findVoter} from '../services/voting'; import {quickCount} from '../services/quick-count';
export const publicRoutes=new Hono<AppEnv>();
publicRoutes.use('/quick-count',requireAdmin);
publicRoutes.use('/api/public/quick-count',requireAdmin);
const requireSuper=async(c:Context<AppEnv>,next:Next)=>{const admin=await c.env.DB.prepare('SELECT role FROM admins WHERE id=?').bind(c.get('adminId')).first();if(admin?.role==='bilik')return c.redirect('/status');await next()};
publicRoutes.use('/quick-count',requireSuper);
publicRoutes.use('/api/public/quick-count',requireSuper);

publicRoutes.use('/status/*',requireAdmin);
publicRoutes.use('/api/status/*',requireAdmin);

const BILIK_COUNT=8;
// Sesuaikan di sini kalau format nama kelas kamu beda (misal 'X-'+n atau 'X '+n)
function bilikClasses(n:number):string[]{return [`X${n}`,`XI${n}`,`XII${n}`]}

publicRoutes.get('/status',c=>{const links=Array.from({length:BILIK_COUNT},(_,i)=>i+1).map(n=>`<a class="btn" href="/status/${n}">Bilik ${n}</a>`).join(' ');return c.html(layout('Status Bilik',`<div class="eyebrow">MONITOR ANTI-GOLPUT</div><h1>Pilih Bilik</h1><p class="muted">Bilik N memantau kelas XN, XIN, XIIN — contoh Bilik 1 memantau X1, XI1, XII1.</p><div class="actions" style="flex-wrap:wrap">${links}</div>`,{admin:true,csrfToken:c.get('csrfToken')}));});

publicRoutes.get('/status/:bilik',c=>{const bilik=Number(c.req.param('bilik'));if(!Number.isInteger(bilik)||bilik<1||bilik>BILIK_COUNT)return c.text('Bilik tidak valid (1-8).',400);const classes=bilikClasses(bilik);return c.html(layout(`Status Bilik ${bilik}`,`<div class="eyebrow">MONITOR ANTI-GOLPUT · BILIK ${bilik}</div><h1>Status Pemilih — ${classes.join(' / ')}</h1><div class="grid" id="summary"></div><div id="content" style="margin-top:18px"><div class="card">Memuat data...</div></div><p id="updated" class="muted"></p><script>const bilik=${bilik};const safe=v=>String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));async function load(){try{const r=await fetch('/api/status/'+bilik);if(!r.ok)throw Error();const rows=await r.json();render(rows);document.querySelector('#updated').textContent='Terakhir diperbarui: '+new Date().toLocaleTimeString('id-ID')}catch(e){document.querySelector('#updated').textContent='Koneksi terputus. Mencoba memperbarui kembali…'}setTimeout(load,5000)}function render(rows){const icon=s=>s==='voted'?'✅':s==='error'?'⚠️':'❌';const label=s=>s==='voted'?'Sudah Memilih':s==='error'?'Akun Belum Siap':'Belum Memilih';const voted=rows.filter(x=>x.status==='voted').length,error=rows.filter(x=>x.status==='error').length;document.querySelector('#summary').innerHTML='<div class="card stat">Total Siswa<strong>'+rows.length+'</strong></div><div class="card stat">Sudah Memilih<strong>'+voted+'</strong></div><div class="card stat">Belum Memilih<strong>'+(rows.length-voted-error)+'</strong></div><div class="card stat">Akun Belum Siap<strong>'+error+'</strong></div>';let h='<div class="table-wrap"><table><thead><tr><th></th><th>Nama</th><th>Kelas</th><th>Status</th></tr></thead><tbody>';for(const x of rows){h+='<tr><td style="font-size:22px">'+icon(x.status)+'</td><td>'+safe(x.name)+'</td><td>'+safe(x.className)+'</td><td>'+label(x.status)+'</td></tr>'}h+='</tbody></table></div>';document.querySelector('#content').innerHTML=rows.length?h:'<div class="card">Belum ada data siswa untuk kelas bilik ini.</div>'}load()</script>`,{admin:true,wide:true,csrfToken:c.get('csrfToken')}));});

publicRoutes.get('/api/status/:bilik',async c=>{const bilik=Number(c.req.param('bilik'));if(!Number.isInteger(bilik)||bilik<1||bilik>BILIK_COUNT)return jsonError(c,400,'Bilik tidak valid.');const classes=bilikClasses(bilik);const rows=await c.env.DB.prepare('SELECT name,class_name,attendance_number,has_voted,username,password_hash FROM students WHERE class_name IN (?,?,?) ORDER BY class_name,attendance_number').bind(...classes).all<{name:string;class_name:string;attendance_number:number;has_voted:number;username:string|null;password_hash:string|null}>();const data=rows.results.map(s=>({name:s.name,className:`${s.class_name} · Absen ${s.attendance_number}`,status:s.has_voted?'voted':(!s.username||!s.password_hash)?'error':'not_voted'}));return c.json(data)});

publicRoutes.get('/',c=>{const error=c.req.query('error');return c.html(layout('Pemilihan OSIS',`<section class="hero"><div class="eyebrow">DEMOKRASI SEKOLAH</div><h1>Suaramu menentukan<br>masa depan OSIS.</h1><p>Pemilihan Ketua & Wakil Ketua OSIS yang aman, anonim, dan transparan.</p><form class="card" method="post" action="/login">${error?`<div class="alert">${esc(error)}</div>`:''}<label>Username</label><input name="username" autocomplete="username" required autofocus><label>Password</label><input type="password" name="password" autocomplete="current-password" required><button style="margin-top:18px;width:100%">Masuk & Mulai Memilih</button></form></section>`))});
publicRoutes.post('/login',async c=>{const b=await body(c),username=String(b.username||'').trim().toLowerCase(),password=String(b.password||'');const fail=(msg:string)=>c.redirect('/?error='+encodeURIComponent(msg));if(!username||!password)return fail('Username dan password wajib diisi.');const key=await sha256(`${ip(c)}:${username}`);const attempt=await c.env.DB.prepare("SELECT attempts,window_started_at FROM login_attempts WHERE key_hash=? AND window_started_at>datetime('now','-15 minutes')").bind(key).first<{attempts:number}>();if((attempt?.attempts??0)>=5)return c.html(layout('Terlalu Banyak Percobaan','<div class="card"><h1>Coba lagi nanti.</h1><p>Terlalu banyak percobaan login.</p></div>'),429);const student=await c.env.DB.prepare('SELECT id,password_hash,has_voted FROM students WHERE username=?').bind(username).first<{id:number;password_hash:string|null;has_voted:number}>();const ok=Boolean(student?.password_hash)&&await verifyPassword(password,student!.password_hash!);if(!ok){await c.env.DB.prepare("INSERT INTO login_attempts(key_hash,attempts,window_started_at) VALUES(?,1,CURRENT_TIMESTAMP) ON CONFLICT(key_hash) DO UPDATE SET attempts=CASE WHEN window_started_at<=datetime('now','-15 minutes') THEN 1 ELSE attempts+1 END,window_started_at=CASE WHEN window_started_at<=datetime('now','-15 minutes') THEN CURRENT_TIMESTAMP ELSE window_started_at END").bind(key).run();return fail('Username atau password salah.')}await c.env.DB.prepare('DELETE FROM login_attempts WHERE key_hash=?').bind(key).run();if(student!.has_voted)return fail('Akun ini sudah digunakan untuk memilih.');const state=await electionState(c.env);if(state?.status!=='OPEN')return fail('Pemilihan belum dibuka. Status saat ini: '+(state?.status||'-'));const token=randomToken(32);const result=await c.env.DB.prepare('UPDATE students SET qr_token_hash=? WHERE id=? AND has_voted=0').bind(await sha256(token),student!.id).run();if(!result.meta.changes)return fail('Gagal memproses login. Coba lagi.');return c.redirect(`/vote?t=${encodeURIComponent(token)}`)});
publicRoutes.get('/vote',async c=>{const token=c.req.query('t')||'';const voter=await findVoter(c.env,token);const state=await electionState(c.env);if(!voter)return c.html(layout('QR Tidak Valid',`<div class="card"><h1>QR Code tidak valid.</h1><p>QR mungkin sudah diganti atau tidak dikenali.</p></div>`),404);if(voter.has_voted)return c.html(layout('Sudah Memilih',`<div class="card"><h1>Anda sudah menggunakan hak suara.</h1></div>`),409);if(state?.status!=='OPEN')return c.html(layout('Pemilihan Ditutup',`<div class="card"><h1>Pemilihan belum tersedia.</h1><p>Status saat ini: ${esc(state?.status)}</p></div>`),403);const cs=await c.env.DB.prepare('SELECT * FROM candidates ORDER BY candidate_number').all<Record<string,unknown>>();const cards=cs.results.map(x=>`<article class="card candidate"><div class="num">${String(x.candidate_number).padStart(2,'0')}</div>${x.photo_url?`<img src="${esc(x.photo_url)}" alt="Foto paslon ${esc(x.candidate_number)}">`:''}<h2>${esc(x.chairman_name)}<br>&amp;<br>${esc(x.vice_chairman_name)}</h2><details><summary>Visi & Misi</summary><p>${esc(x.vision)}</p><p>${esc(x.mission)}</p></details><button onclick="pick(${Number(x.id)},'${esc(x.candidate_number)}','${esc(x.chairman_name)} & ${esc(x.vice_chairman_name)}')">Pilih ${String(x.candidate_number).padStart(2,'0')}</button></article>`).join('');return c.html(layout('Pilih Paslon',`<div class="eyebrow">PEMILIHAN KETUA & WAKIL KETUA OSIS</div><h1>Gunakan hak suara Anda</h1><div class="card"><strong>${esc(voter.name)}</strong> · ${esc(voter.class_name)} · Absen ${voter.attendance_number}</div><div class="grid" style="margin-top:20px">${cards}</div><dialog id="confirm"><h2>Konfirmasi pilihan</h2><p>Anda memilih <strong id="choice"></strong>.</p><p class="alert">Pilihan tidak dapat diubah setelah dikirim.</p><div class="actions"><button class="secondary" onclick="confirm.close()">Kembali</button><button id="send">Kirim Suara</button></div></dialog><script>let selected;const confirm=document.querySelector('#confirm');function pick(id,num,names){selected=id;document.querySelector('#choice').textContent='PASLON '+num+' — '+names;confirm.showModal()}document.querySelector('#send').onclick=async()=>{const b=document.querySelector('#send');b.disabled=true;const r=await fetch('/api/vote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:${JSON.stringify(token)},candidateId:selected})});if(r.ok)location.replace('/success');else{const j=await r.json();alert(j.error||'Suara gagal dikirim');b.disabled=false}};</script>`));});
publicRoutes.post('/api/vote',async c=>{const b=await body(c),token=String(b.token||''),candidateId=Number(b.candidateId);if(!Number.isInteger(candidateId))return jsonError(c,400,'Pilihan tidak valid.');const ok=await castAnonymousVote(c.env,token,candidateId);return ok?c.json({ok:true}):jsonError(c,409,'Suara tidak dapat diproses. Token mungkin sudah digunakan atau pemilihan tidak dibuka.');});
publicRoutes.get('/success',c=>c.html(layout('Terima Kasih',`<section class="hero"><div class="eyebrow ok">SUARA TEREKAM</div><h1>Terima kasih.</h1><p>Suara Anda telah berhasil direkam.</p><div class="actions"><a class="btn" href="/">Selesai</a></div></section><script>history.replaceState(null,'','/success')</script>`)));
publicRoutes.get('/api/public/quick-count',async c=>{const data=await quickCount(c.env);c.header('Cache-Control','public, max-age=3');if(!data.enabled)return c.json({enabled:false,status:data.status,electionName:data.electionName,schoolName:data.schoolName});if(data.mode==='PARTICIPATION_ONLY')return c.json({...data,candidates:[]});if(data.mode==='PERCENTAGE_ONLY')return c.json({...data,candidates:data.candidates.map(({votes:_,...candidate})=>candidate)});return c.json(data)});
publicRoutes.get('/quick-count',c=>{const screen=c.req.query('display')==='screen';return c.html(layout('Quick Count',`<section class="${screen?'screen':''}"><div class="eyebrow">● LIVE</div><h1 id="title">QUICK COUNT</h1><p id="school" class="muted"></p><div id="content" class="grid"><div class="card">Memuat hasil...</div></div><p id="updated" class="muted"></p></section><script>let last;async function load(){try{const r=await fetch('/api/public/quick-count');if(!r.ok)throw Error();const d=await r.json();last=d;render(d)}catch(e){document.querySelector('#updated').textContent='Koneksi terputus. Mencoba memperbarui kembali…'}setTimeout(load,Math.max(3000,(last?.refreshInterval||5)*1000))}function render(d){document.querySelector('#title').textContent=d.status==='CLOSED'?'HASIL AKHIR':'QUICK COUNT — HASIL SEMENTARA';document.querySelector('#school').textContent=d.schoolName||'';if(!d.enabled){content.innerHTML='<div class="card"><h2>Quick Count belum tersedia</h2></div>';return}let h='<div class="card stat"><span>Total Pemilih</span><strong>'+d.totalStudents+'</strong></div><div class="card stat"><span>Suara Masuk</span><strong>'+d.totalVotes+'</strong></div><div class="card stat"><span>Partisipasi</span><strong>'+d.turnoutPercentage+'%</strong><div class="progress"><i style="width:'+d.turnoutPercentage+'%"></i></div></div>';for(const c of d.candidates){h+='<div class="card candidate"><div class="num">'+String(c.candidateNumber).padStart(2,'0')+'</div><h2>'+c.chairmanName+' & '+c.viceChairmanName+'</h2>'+(c.percentage!==undefined?'<strong style="font-size:38px">'+c.percentage+'%</strong>':'')+(c.votes!==undefined?'<p>'+c.votes+' suara</p>':'')+'</div>'}content.innerHTML=h;updated.textContent='Terakhir diperbarui: '+new Date().toLocaleTimeString('id-ID')}load()</script>`,{wide:screen}));});

