const concat=(parts:Uint8Array[])=>{const length=parts.reduce((sum,part)=>sum+part.length,0),out=new Uint8Array(length);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length}return out};
const u32=(value:number)=>new Uint8Array([(value>>>24)&255,(value>>>16)&255,(value>>>8)&255,value&255]);
const crcTable=(()=>{const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0}return table})();
const crc32=(data:Uint8Array)=>{let crc=0xffffffff;for(const byte of data)crc=crcTable[(crc^byte)&255]^(crc>>>8);return (crc^0xffffffff)>>>0};
const chunk=(type:string,data:Uint8Array)=>{const name=new TextEncoder().encode(type),payload=concat([name,data]);return concat([u32(data.length),payload,u32(crc32(payload))])};
const adler32=(data:Uint8Array)=>{let a=1,b=0;for(const byte of data){a=(a+byte)%65521;b=(b+a)%65521}return ((b<<16)|a)>>>0};
const deflateStored=(data:Uint8Array)=>{const parts:Uint8Array[]=[new Uint8Array([0x78,0x01])];for(let offset=0;offset<data.length;){const length=Math.min(65535,data.length-offset),final=offset+length>=data.length;parts.push(new Uint8Array([final?1:0,length&255,(length>>>8)&255,(~length)&255,((~length)>>>8)&255]));parts.push(data.subarray(offset,offset+length));offset+=length}parts.push(u32(adler32(data)));return concat(parts)};

export function qrMatrixToPng(size:number,getModule:(row:number,col:number)=>number,scale=10,margin=4){const width=(size+margin*2)*scale,rowLength=width+1,raw=new Uint8Array(rowLength*width);for(let y=0;y<width;y++){const rowOffset=y*rowLength;raw[rowOffset]=0;const moduleRow=Math.floor(y/scale)-margin;for(let x=0;x<width;x++){const moduleCol=Math.floor(x/scale)-margin;const dark=moduleRow>=0&&moduleRow<size&&moduleCol>=0&&moduleCol<size&&getModule(moduleRow,moduleCol);raw[rowOffset+1+x]=dark?0:255}}const ihdr=concat([u32(width),u32(width),new Uint8Array([8,0,0,0,0])]);return concat([new Uint8Array([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('IDAT',deflateStored(raw)),chunk('IEND',new Uint8Array())])}
